Repository gip-inclusion/dora, pull requests merged in 2024-10, with the labels that each got.

#32 [HOTFIX] _get_di_results(): gère le cas où le champ thematiques est nul
  back/dora/services/search.py
Labels: bug

#1 docs: proposition d'ADR pour passer d'un multirepo (front + back) à un monorepo
  .gitignore
  back/.gitignore
  docs/adr/001-migrer-le-code-vers-un-monorepo.md
Labels: documentation

#21 Recherche de structures par le nom pour les admins et managers
  front/src/lib/components/forms/fields/select-field.svelte
  front/src/lib/components/inputs/select/select.svelte
  front/src/lib/components/inputs/select/simple-autocomplete.svelte
  front/src/lib/requests/structures.ts
  front/src/lib/utils/misc.ts
  front/src/routes/(modeles-services)/_common/fields-structure.svelte
  front/src/routes/(modeles-services)/services/creer/+page.svelte
  front/src/routes/(modeles-services)/services/creer/+page.ts
  front/src/routes/(modeles-services)/services/service-edition-form.svelte
Labels: feature

#26 envs-example/dev.env: mise à jour de DATA_INCLUSION_URL
  back/envs-example/dev.env
Labels: documentation

#25 README.md: ajout d'un commentaire sur l'import des données géographiques
  back/README.md
Labels: documentation

#22 Page recherche: sélection par défaut du filtre de lieu d'accueil « En présentiel »
  front/src/routes/recherche/+page.svelte
Labels: feature

#27 bugfix: ne pas afficher l'adresse quand elle n'est pas renseignée
  front/src/routes/recherche/search-result.svelte
Labels: bug
