Repository gip-inclusion/dora, pull requests merged in 2025-01, with the labels that each got.

#150 Catégorisation des actions pour les connexions directes
  back/dora/auth_links/enums.py
  back/dora/auth_links/views.py
Labels: chore

#151 fix: Correction de la fonction de formattage de numéro de téléphone + tests
  front/src/lib/utils/misc.ts
  front/src/tests/utils/misc/formatPhoneNumber.test.ts
Labels: bug

#158 ci(pr): Ajout d'une action GitHub de validation du titre de la PR
  .github/workflows/lint-pr.yml
Labels: chore

#152 fix(sitemap): Sitemap paginé
  front/src/lib/consts.ts
  front/src/lib/requests/services.ts
  front/src/lib/requests/structures.ts
  front/src/lib/utils/date.ts
  front/src/routes/(endpoints)/sitemap-services-[page].xml/+server.ts
  front/src/routes/(endpoints)/sitemap-structures-[page].xml/+server.ts
  front/src/routes/(endpoints)/sitemap.xml/+server.ts
Labels: bug

#159 feat: Fréquence de mise à jour des services
  back/config/settings/base.py
  back/dora/core/templates/email_services_check.html
  back/dora/data_inclusion/mappings.py
  back/dora/services/management/commands/send_services_reminders.py
  back/dora/services/migrations/0115_service_update_frequency.py
  back/dora/services/models.py
  back/dora/services/serializers.py
  back/dora/services/tests/test_services_reminders.py
  back/dora/services/views.py
  front/src/lib/types.ts
  front/src/lib/validation/schemas/service.ts
  front/src/routes/(modeles-services)/_common/fields-periodicity.svelte
Labels: feature

#207 fix: normalisation des adresses e-mail
  back/dora/core/management/commands/import_ft_users.py
  back/dora/core/management/commands/import_structures.py
  back/dora/oidc/backends.py
  back/dora/oidc/utils.py
  back/dora/oidc/views.py
  back/dora/rest_auth/views.py
  back/dora/structures/serializers.py
  back/dora/structures/tests/test_structures.py
  back/dora/users/management/commands/merge_users.py
  back/dora/users/migrations/0030_normalize_emails.py
  back/dora/users/models.py
  back/dora/users/tests/test_user_manager.py
  back/scripts/import_cresus_structures.py
Labels: bug, python

#208 fix: suppression du formatage des horaires du service
  front/src/lib/components/specialized/services/display/extended-service-key-informations.svelte
  front/src/lib/components/specialized/services/display/service-key-informations.svelte
  front/src/lib/utils/opening-hours.ts
Labels: bug
